paths:
  raw_zone: "/app/data/raw_zone"
  standard_zone: "/app/data/standard_zone"
  consumption_zone: "/app/data/consumption_zone"
  rejection_zone: "/app/data/rejection_zone"
  input_file: "energy_usage.csv"
app_name: "EnergyUsagePipeline"
file_name: "energy_usage"